Repository smartrent/grizzly, pull requests merged in 2024-01, with the labels that each got.

#880 release v7.1.1
  CHANGELOG.md
  mix.exs
Labels: ignore-for-release

#881 Elixir 1.16 compatibility
  .circleci/config.yml
  .tool-versions
  lib/grizzly/firmware_updates/firmware_update_runner/image.ex
Labels: enhancement

#890 Implement missing Meter CC commands
  lib/grizzly/commands/table.ex
  lib/grizzly/zwave/command_classes/meter.ex
  lib/grizzly/zwave/commands/meter_report.ex
  lib/grizzly/zwave/commands/meter_reset.ex
  lib/grizzly/zwave/commands/meter_supported_get.ex
  lib/grizzly/zwave/commands/meter_supported_report.ex
  lib/grizzly/zwave/decoder.ex
  test/grizzly/zwave/commands/meter_reset_test.exs
  test/grizzly/zwave/commands/meter_supported_get_test.exs
  test/grizzly/zwave/commands/meter_supported_report_test.exs
Labels: enhancement

#893 Fix incorrect catch clause match
  lib/grizzly/connections/supervisor.ex
Labels: bug

#894 release v7.2.0
  CHANGELOG.md
  mix.exs
Labels: ignore-for-release
