Repository smartrent/grizzly, pull requests merged in 2024-04, with the labels that each got.

#920 release v8.0.1
  CHANGELOG.md
  mix.exs
Labels: ignore-for-release

#921 Update Alpine Version in CircleCI Config
  .circleci/config.yml
Labels: maintenance

#923 Implement Included NIF Report command
  lib/grizzly/zwave/commands/included_nif_report.ex
  lib/grizzly/zwave/decoder.ex
  lib/grizzly/zwave/dsk.ex
Labels: enhancement

#922 Improve firmware updates for wakeup devices
  lib/grizzly/commands/command.ex
  lib/grizzly/firmware_updates.ex
  lib/grizzly/firmware_updates/firmware_update_runner.ex
  lib/grizzly/firmware_updates/firmware_update_runner/firmware_update.ex
Labels: enhancement
