Repository smartrent/grizzly, pull requests merged in 2024-02, with the labels that each got.

#895 Add missing commands to SensorMultilevel CC
  lib/grizzly/commands/table.ex
  lib/grizzly/zwave/command_classes/sensor_multilevel.ex
  lib/grizzly/zwave/commands/sensor_multilevel_supported_scale_get.ex
  lib/grizzly/zwave/commands/sensor_multilevel_supported_scale_report.ex
  lib/grizzly/zwave/decoder.ex
  test/grizzly/zwave/commands/sensor_multilevel_supported_scale_get_test.exs
  test/grizzly/zwave/commands/sensor_multilevel_supported_scale_report_test.exs
  test/grizzly/zwave/commands/sensor_multilevel_supported_sensor_report_test.exs
Labels: enhancement

#896 Ignore extra trailing bytes when decoding ThermostatSetpointReport
  lib/grizzly/zwave/commands/thermostat_setpoint_report.ex
  test/grizzly/zwave/commands/thermostat_setpoint_report_test.exs
Labels: enhancement

#887 Encode extended node id correctly in `S2ResynchronizationEvent`
  lib/grizzly/zwave/commands/s2_resynchronization_event.ex
  test/grizzly/zwave/commands/s2_resynchronization_event_test.exs
Labels: bug

#903 release v7.4.0
  CHANGELOG.md
  mix.exs
Labels: ignore-for-release
